version: "3.3"
services:
  campaignmodule:    
    container_name: campaignmodule
    build:      
      context: ..
      dockerfile: CampaignModule/CampaignModuleApi/Dockerfile   
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on: [ mssql ]
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend       


  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: mssql
    hostname: mssql
    environment:
      SA_PASSWORD: "Pass123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express

    restart: unless-stopped    
    ports:
      - "1433:1433"
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

networks:
  backend:
    driver: "bridge" 